### ISSUE TITLE
Si l'index.jmxtrans n'est pas créé le backend ne fonctionne pas

### ISSUE THREAD

**Issue by pmioulet** [btravers/Back#4]
Si on installe l'application sans créer l'index sur le serveur ES toutes les requêtes échouent:
cf:
GRAVE: Servlet.service() for servlet [back] in context with path [/jmxtrans-gui] threw exception [Request processing failed; nested exception is org.elasticsearch.indices.IndexMissingException: [.jmxtrans] missing] with root cause
org.elasticsearch.indices.IndexMissingException: [.jmxtrans] missing
        at org.elasticsearch.cluster.metadata.MetaData.convertFromWildcards(MetaData.java:795)
        at org.elasticsearch.cluster.metadata.MetaData.concreteIndices(MetaData.java:667)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.<init>(TransportSearchTypeAction.java:113)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction.<init>(TransportSearchQueryThenFetchAction.java:68)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction.<init>(TransportSearchQueryThenFetchAction.java:62)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction.doExecute(TransportSearchQueryThenFetchAction.java:59)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction.doExecute(TransportSearchQueryThenFetchAction.java:49)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:65)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:101)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:43)

**Comment by btravers** [comment]
Problème résolu après le merges de branches.
